
cluster: marius
token: 73747bb7c61632155d00e0baf628211a79efb8feee7d0928810feaaddac8874e
sshkey: /Users/thebes/.ssh/marius
max_threads: 10
coldkey: marius
machines:
  M0:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"

  M1:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64    
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"

  M2:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name gpt2-medium"

  M3:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"
  
  M4:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"

  M5:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"

  M6:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"

  M7:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased"

  M8:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name gpt2-medium"

  M9:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased"

  M10:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased"

  
  M11:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased"

  M12:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased"

  M13:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    command: /root/.bittensor/bittensor/bittensor/_neuron/text/advanced_server/main.py
    args: "--subtensor.network nakamoto --wandb.api_key 40177b21a9f074650eff24ebbb085daa066ddb97 --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased"
      